services: 
  # basic-image: ubuntu:22.04
  maindev_ubuntu22:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ubuntu:latest
    container_name: maindev_ubuntu22
    init: true
    ports:
      - "8080:80"
    network_mode: host
    ipc: host
    restart: always
    privileged: true
    tty: true
    shm_size: 268M
    # runtime: nvidia
    # environment: 
    #   NVIDIA_VISIBLE_DEVICES: all
    volumes:
      # - /home/nemo/:/exec
      - ../workspace:/workspace

